name: Deploy Failure Analysis App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy on Windows server
      run: |
        $projectPath = 'C:\Users\Administrator\Documents\Failure Analysis'

        # Navigate to project folder
        Set-Location $projectPath

        # Reset any local changes and pull latest code
        git reset --hard
        git clean -fd
        git pull origin main

        # Create virtual environment if it doesn't exist
        if (-not (Test-Path "$projectPath\venv")) {
            python -m venv venv
        }

        # Install/update dependencies
        .\venv\Scripts\python.exe -m pip install --upgrade pip
        .\venv\Scripts\python.exe -m pip install -r requirements.txt

        # Stop any running Python app
        Get-Process python -ErrorAction SilentlyContinue | Stop-Process -Force

        # Start the app in background
        Start-Process -FilePath .\venv\Scripts\python.exe -ArgumentList "$projectPath\app.py" -WorkingDirectory $projectPath
