name: Deploy Failure Analysis App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy on Windows server
      shell: pwsh
      run: |
        $projectPath = "C:\Users\Administrator\Documents\Failure Analysis"

        # Verify path exists
        if (-not (Test-Path $projectPath)) {
            Write-Host "❌ ERROR: Project path not found: $projectPath"
            exit 1
        }

        Write-Host "✅ Found project path: $projectPath"
        Set-Location $projectPath

        # Reset local changes and pull latest from main
        git reset --hard
        git clean -fd
        git pull origin main

        # Create virtual environment if missing
        if (-not (Test-Path "$projectPath\venv")) {
            python -m venv venv
        }

        # Install/update dependencies
        & "$projectPath\venv\Scripts\python.exe" -m pip install --upgrade pip
        & "$projectPath\venv\Scripts
