name: Deploy Failure Analysis App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy on Windows server
      run: |
        cd C:\Users\Administrator\Documents\Failure Analysis
        git pull origin main
        if (-not (Test-Path "venv")) {
            python -m venv venv
        }
        .\venv\Scripts\Activate.ps1
        pip install --upgrade pip
        pip install -r requirements.txt
        Get-Process python -ErrorAction SilentlyContinue | Stop-Process -Force
        Start-Process powershell -ArgumentList '-NoProfile -WindowStyle Hidden -Command "cd \"C:\Users\Administrator\Documents\Failure Analysis\"; .\venv\Scripts\python.exe app.py"'
